"""retry backoff for content fetching

Revision ID: 4b46d1ea45d7
Revises: af783c4d4200
Create Date: 2026-10-02 04:43:49.739946

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4b46d1ea45d7"
down_revision: str | Sequence[str] | None = "af783c4d4200"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "articles", sa.Column("content_next_attempt_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("articles", "content_next_attempt_at")
    # ### end Alembic commands ###
