"""track content fetch attempts

Revision ID: af783c4d4200
Revises: 186581fbd5fb
Create Date: 2026-10-02 03:52:48.098865

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "af783c4d4200"
down_revision: str | Sequence[str] | None = "186581fbd5fb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "articles", sa.Column("content_attempts", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column("articles", sa.Column("content_error", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("articles", "content_error")
    op.drop_column("articles", "content_attempts")
    # ### end Alembic commands ###
